openapi: 3.0.3
info:
  title: FlashDash Notification Service API
  description: |
    The FlashDash Notification Service API manages the sending of email notifications 
    and in-app notifications for users. The service handles email confirmations, 
    friend invitations, and daily reminder notifications.
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:9090
    description: Local development server for Notification Service

tags:
  - name: Email Notifications
    description: Endpoints for sending email notifications to users.

paths:
  /notifications/confirm-account:
    post:
      tags:
        - Email Notifications
      summary: Send account confirmation email
      description: |
        Sends an email to the user with a confirmation link for activating their account.
      security:
        - bearerAuth: []
      operationId: sendAccountConfirmationEmail
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
          description: "Account confirmation token to be included in the verification link."
      responses:
        "202":
          description: Confirmation email sent successfully
        "401":
          description: Unauthorized - Token Missing or Invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Token Missing or Invalid:
                  $ref: "#/components/examples/ErrorResponseExample401_TokenMissingOrInvalid"

  /notifications/friend-invite:
    post:
      tags:
        - Email Notifications
      summary: Send friend invitation email
      description: |
        Sends an email notification to a user when they receive a friend invitation.
      security:
        - bearerAuth: []
      operationId: sendFriendInviteEmail
      responses:
        "202":
          description: Friend invitation email sent successfully
        "401":
          description: Unauthorized - Token Missing or Invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Token Missing or Invalid:
                  $ref: "#/components/examples/ErrorResponseExample401_TokenMissingOrInvalid"

  /notifications/daily/enable:
    post:
      tags:
        - Email Notifications
      summary: Enable daily notifications
      description: |
        Enables daily notifications for the authenticated user.
        The service will send daily reminders at a fixed time.
      security:
        - bearerAuth: []
      operationId: enableDailyNotifications
      responses:
        "200":
          description: Daily notifications enabled successfully
        "401":
          description: Unauthorized - Token Missing or Invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Token Missing or Invalid:
                  $ref: "#/components/examples/ErrorResponseExample401_TokenMissingOrInvalid"

  /notifications/daily/disable:
    post:
      tags:
        - Email Notifications
      summary: Disable daily notifications
      description: |
        Disables daily notifications for the authenticated user.
      security:
        - bearerAuth: []
      operationId: disableDailyNotifications
      responses:
        "200":
          description: Daily notifications disabled successfully
        "401":
          description: Unauthorized - Token Missing or Invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Token Missing or Invalid:
                  $ref: "#/components/examples/ErrorResponseExample401_TokenMissingOrInvalid"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authentication scheme using Bearer token with JWT."

  schemas:
    ErrorResponse:
      type: object
      description: "Error response structure."
      properties:
        status:
          type: integer
          description: "HTTP status code of the error."
        error:
          type: string
          description: "Error message."
        cause:
          type: string
          description: "Cause of the error."
        action:
          type: string
          description: "Suggested action to resolve the error."
        timestamp:
          type: string
          format: date-time
          description: "Time when the error occurred."
        correlationId:
          type: string
          description: "Unique identifier for tracking the error."

  examples:
    ErrorResponseExample401_TokenMissingOrInvalid:
      value:
        status: 401
        error: "E401001"
        cause: "Token is missing or invalid"
        action: "Provide a valid authentication token"
        timestamp: "2025-03-06T12:10:00Z"
        correlationId: "d4e5f6g7"
